FROM debian:buster

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get -yq --no-install-recommends \
  --force-yes install \
  curl \
  dpkg-dev \
  devscripts \
  build-essential \
  lsb-release \
  ruby \
  ruby-dev \
  rubygems-integration \
  && apt-get clean
RUN gem install --no-ri --no-rdoc fpm 

COPY ./docker-entrypoint.sh /
COPY ./build-deb.sh /

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/build-deb.sh"]
