atella:
  atellaConfig: "/etc/atella/atella.conf"
  masterServersConfig: "/etc/atella/conf.d/master_servers.conf"
  sectorsConfig: "/etc/atella/conf.d/sectors.conf"
  securityConfig: "/etc/atella/conf.d/sec.conf"
  filesDirectory: "/usr/share/atella/"
  packagesDirectory: "pkg/"
  configsDirectory: "cfg/"
  