#!/bin/sh

set -e

if ! getent group "atella" > /dev/null 2>&1 ; then
  groupadd -r "atella"
fi

if ! getent passwd "atella" > /dev/null 2>&1 ; then
  useradd -m -r -g atella -d /usr/share/atella -s /sbin/nologin \
    -c "Atella user" atella
fi

if [ -x /bin/systemctl ] ; then
  /bin/systemctl daemon-reload
  /bin/systemctl enable atella.service
  /bin/systemctl status atella.service >> /dev/null 2>&1
  if [ $status -eq 0 ]; then
      /bin/systemctl restart atella.service
  else
      /bin/systemctl start atella.service
  fi
elif [ -x /sbin/chkconfig ] ; then
  /sbin/chkconfig --add atella
fi
