#!/bin/sh

set -e

if ! getent group "atella" > /dev/null 2>&1 ; then
  groupadd -r "atella"
fi

if ! getent passwd "atella" > /dev/null 2>&1 ; then
  useradd -m -r -g atella -d /usr/share/atella -s /sbin/nologin \
    -c "Atella user" atella
fi

if [ -x /bin/systemctl ] ; then
  /bin/systemctl daemon-reload
  /bin/systemctl enable atella.service
elif [ -x /sbin/chkconfig ] ; then
  /sbin/chkconfig --add atella
fi
